N0:	MOVLW	'0'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N2:	MOVLW '2'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N4:	MOVLW '4'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N6:	MOVLW '6'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N8:	MOVLW '8'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N10:	MOVLW '1'
	CALL Send_Serial
	MOVLW '0'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N12:    MOVLW '1'
	CALL Send_Serial
	MOVLW	'2'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N14:    MOVLW '1'
	CALL Send_Serial
        MOVLW '4'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN

N16:    MOVLW '1'
	CALL Send_Serial
        MOVLW '6'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN


N18:    MOVLW '1'
	CALL Send_Serial
        MOVLW '8'
	CALL Send_Serial
    MOVLW   ' '
    CALL    Send_Serial
	RETURN


N20:    MOVLW '2'
	CALL Send_Serial
        MOVLW '0'
	CALL Send_Serial
	RETURN


N22:    MOVLW '2'
	CALL Send_Serial
        MOVLW '2'
	CALL Send_Serial
	RETURN


N24:    MOVLW '2'
	CALL Send_Serial
        MOVLW '4'
	CALL Send_Serial
	RETURN


N26:    MOVLW '2'
	CALL Send_Serial
        MOVLW '6'
	CALL Send_Serial
	RETURN


N28:    MOVLW '2'
	CALL Send_Serial
        MOVLW '8'
	CALL Send_Serial
	RETURN


N30:    MOVLW '3'
	CALL Send_Serial
        MOVLW '0'
	CALL Send_Serial
	RETURN


N32:    MOVLW '3'
	CALL Send_Serial
        MOVLW '2'
	CALL Send_Serial
	RETURN


N34:    MOVLW '3'
	CALL Send_Serial
        MOVLW '4'
	CALL Send_Serial
	RETURN


N36:    MOVLW '3'
	CALL Send_Serial
        MOVLW '6'
	CALL Send_Serial
	RETURN


N38:    MOVLW '3'
	CALL Send_Serial
        MOVLW '8'
	CALL Send_Serial
	RETURN


N40:    MOVLW '4'
	CALL Send_Serial
        MOVLW '0'
	CALL Send_Serial
	RETURN


N42:    MOVLW '4'
	CALL Send_Serial
        MOVLW '2'
	CALL Send_Serial
	RETURN


N44:    MOVLW '4'
	CALL Send_Serial
        MOVLW '4'
	CALL Send_Serial
	RETURN


N46:    MOVLW '4'
	CALL Send_Serial
        MOVLW '6'
	CALL Send_Serial
	RETURN


N48:    MOVLW '4'
	CALL Send_Serial
        MOVLW '8'
	CALL Send_Serial
	RETURN


N50:    MOVLW '5'
	CALL Send_Serial
        MOVLW '0'
	CALL Send_Serial
	RETURN


N52:    MOVLW '5'
	CALL Send_Serial
        MOVLW '2'
	CALL Send_Serial
	RETURN


N54:    MOVLW '5'
        CALL Send_Serial
        MOVLW '4'
        CALL Send_Serial
        RETURN


N56:    MOVLW '5'
	CALL Send_Serial
        MOVLW '6'
	CALL Send_Serial
	RETURN


N58:    MOVLW '5'
	CALL Send_Serial
        MOVLW '8'
	CALL Send_Serial
	RETURN


N60:    MOVLW '6'
	CALL Send_Serial
        MOVLW '0'
	CALL Send_Serial
	RETURN


N62:    MOVLW '6'
	CALL Send_Serial
        MOVLW '2'
	CALL Send_Serial
	RETURN


N64:    MOVLW '6'
	CALL Send_Serial
        MOVLW '4'
	CALL Send_Serial
	RETURN


N66:    MOVLW '6'
	CALL Send_Serial
        MOVLW '6'
	CALL Send_Serial
	RETURN


N68:    MOVLW '6'
	CALL Send_Serial
        MOVLW '8'
	CALL Send_Serial
	RETURN


N70:    MOVLW '7'
	CALL Send_Serial
        MOVLW '0'
	CALL Send_Serial
	RETURN


N72:    MOVLW '7'
	CALL Send_Serial
        MOVLW '2'
	CALL Send_Serial
	RETURN


N74:    MOVLW '7'
	CALL Send_Serial
        MOVLW '4'
	CALL Send_Serial
	RETURN


N76:    MOVLW '7'
	CALL Send_Serial
        MOVLW '6'
	CALL Send_Serial
	RETURN


N78:    MOVLW '7'
	CALL Send_Serial
        MOVLW '8'
	CALL Send_Serial
	RETURN


N80:    MOVLW '8'
	CALL Send_Serial
        MOVLW '0'
	CALL Send_Serial
	RETURN